[versions]
androidx-activity = "1.10.1"
androidx-coreKTX = "1.15.0"
androidx-appCompat = "1.7.0"
androidx-interpolator = "1.0.0"
androidx-recyclerview = "1.4.0"
androidx-transition = "1.5.1"
androidx-biometrics = "1.4.0-alpha02"
androidx-collection = "1.5.0"
androidx-fragment = "1.8.6"
androidx-lifecycle = "2.8.7"
androidx-documentFile = "1.0.1"
androidx-constraintlayout = "2.2.1"
androidx-exifinterface = "1.4.0"
androidx-paletteKtx = "1.0.0"
androidx-preferenceKtx = "1.2.1"
androidx-swiperefreshlayout = "1.1.0"
androidx-vectordrawable = "1.2.0"
androidx-viewpager2 = "1.1.0"
androidx-securityVersion = "1.1.0-alpha06"
androidx-annotation = "1.9.1"
androidx-test-core = '1.6.1'
archTestingVersion = "2.2.0"
coroutines = "1.10.1"
espressoCore = "3.6.1"
hamcrestVersion = "1.3"
moshi = "1.15.2"
navigationFragmentKtx = "2.8.9"
okHttp = "4.12.0"
retrofit = "2.11.0"
robolectricVersion = "4.14.1"
roomKtx = "2.6.1"
rx = "3.0.1"
glide = "4.16.0"
gson = "2.12.1"
turbine = "1.2.0"
jupiter_version = "5.12.1"
joda = "2.13.0.1"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlinReflect = "2.1.20"
material = "1.12.0"
kotlin = "2.1.20"
ksp = "2.1.20-1.0.32"
kotlin-immutable-collections = "0.3.8"
#Compose
composeActivity = "1.10.1"
compose = "1.7.8"
composeCompiler = "1.5.14"
composeMaterial3 = "1.3.1"
#Gradle
gradlePlugins-agp = "8.9.1"
gradlePlugins-spotless = "7.0.2"
gradlePlugins-dokka = "2.0.0"
gradlePlugins-maven-publish = "maven-publish"
#Build
app-build-compileSDKVersion = "35"
app-build-targetSDK = "35"
app-build-minimumSDK = "21"
app-build-testRunner = "androidx.test.runner.AndroidJUnitRunner"
app-build-kotlinJVMTarget = "17"
app-build-jVMTarget = "JVM_17"
app-build-javaVersion = "VERSION_17"
#versioning
app-version-appId = "dev.funkymuse.setofusefulkotlinextensions"
app-version-versionCode = "1"
app-version-versionName = "1.0.0"

[libraries]
adapter-rxjava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }
android-joda = { module = "net.danlew:android.joda", version.ref = "joda" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appCompat" }
androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "androidx-appCompat" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "androidx-biometrics" }
androidx-collection-ktx = { module = "androidx.collection:collection-ktx", version.ref = "androidx-collection" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-coreKTX" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "archTestingVersion" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "androidx-documentFile" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-interpolator = { module = "androidx.interpolator:interpolator", version.ref = "androidx-interpolator" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junitVersion" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-reactivestreams = { module = "androidx.lifecycle:lifecycle-reactivestreams", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
#Android X lifecycle
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle" }

androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "androidx-paletteKtx" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preferenceKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preferenceKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtx" }
androidx-security-crypto-ktx = { module = "androidx.security:security-crypto-ktx", version.ref = "androidx-securityVersion" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-transition = { module = "androidx.transition:transition", version.ref = "androidx-transition" }
androidx-vectordrawable = { module = "androidx.vectordrawable:vectordrawable", version.ref = "androidx-vectordrawable" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager2" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test-core" }
androidx-androidTestImplementation-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-core" }
androidx-androidTestImplementation-test-ui-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-androidTestImplementation-test-ui-junit-ext = { module = "androidx.test.ext:junit-ktx", version.ref = "junitVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hamcrest-all = { module = "org.hamcrest:hamcrest-all", version.ref = "hamcrestVersion" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }
material = { module = "com.google.android.material:material", version.ref = "material" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectricVersion" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rx" }
rxkotlin = { module = "io.reactivex.rxjava3:rxkotlin", version.ref = "rx" }
kotlin-immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutable-collections" }
#Compose
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-uiTooling-debug = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-uiTooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
# Dependencies of the included build-logic
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugins-agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
test-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
testImplementation-compose-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
testImplementation-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter_version" }
testImplementation-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter_version" }
testImplementation-runtime-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter_version" }
[bundles]
compose = [
    "compose-activity",
    "compose-animation",
    "compose-foundation",
    "compose-material-icons",
    "compose-material3",
    "compose-runtime",
    "compose-ui",
    "compose-uiTooling-preview",
]
lifecycle = [
    "androidx-lifecycle-compose",
    "androidx-lifecycle-process",
    "androidx-lifecycle-runtime",
    "androidx-lifecycle-service",
    "androidx-lifecycle-viewModel",
    "androidx-lifecycle-viewModel-compose",
]
compose-preview = [
    "compose-uiTooling-debug",
]
coroutines = [
    "kotlinx-coroutines-android",
    "kotlinx-coroutines-core"
]
unit-test = [
    "junit",
    "hamcrest-all",
    "androidx-junit-ktx",
    "androidx-test-core-ktx",
    "robolectric",
    "androidx-core-testing",
    "kotlinx-coroutines-test"
]
android-test = [
    "androidx-junit",
    "androidx-espresso-core",
    "androidx-test-core-ktx",
    "androidx-androidTestImplementation-test-rules",
    "androidx-androidTestImplementation-test-ui-junit",
    "androidx-androidTestImplementation-test-ui-junit-ext",
    "test-coroutines",
    "test-turbine",
]
[plugins]
java-library = { id = "java-library" }
test = { id = "com.android.test", version.ref = "gradlePlugins-agp" }
spotless = { id = "com.diffplug.spotless", version.ref = "gradlePlugins-spotless" }
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
library = { id = "com.android.library", version.ref = "gradlePlugins-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "gradlePlugins-dokka" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
convention-compose-app = { id = "convention.android.compose.app" }
convention-compose-library = { id = "convention.android.compose.library" }
convention-moshi = { id = "convention.android.moshi" }
convention-room = { id = "convention.android.room" }
convention-app = { id = "convention.android.app" }
convention-library = { id = "convention.android.library" }
convention-kotlin-library = { id = "convention.android.kotlin.library" }